### ISSUE TITLE
Tasks.tsxでデータが取得できていない。

### ISSUE THREAD

**Issue by AyatoYoshizawa** [AyatoYoshizawa/todo_app#10]
- エラー文
Tasks.tsx:23 ERROR FetchError: The request failed and the interceptors did not return an alternative response
    at DefaultApi.fetchApi (runtime.ts:221:23)
    at async DefaultApi.request (runtime.ts:136:26)
    at async DefaultApi.getTasksApiV1TasksListGetRaw (DefaultApi.ts:187:26)
    at async DefaultApi.getTasksApiV1TasksListGet (DefaultApi.ts:202:26)
onError	@	Tasks.tsx:23

**Comment by jhelom** [comment]
サーバー側のSQLiteのデータファイルを一旦削除してみて。もしかしたら。。。

あとは、下記にも書いのだけど、FastAPI の /docs の画面(swagger)からAPI叩いてみて。
https://github.com/AyatoYoshizawa/todo_app/issues/11#issuecomment-2088311624

まずは、フロントエンドとバッグエンドのどっちに問題があるのかを切り分ける必要があって、作る順序としては、バックエンド単体で動くようにしてから、次にフロントエンド、という感じ。
